# =============================================================================
Parameters:
# =============================================================================

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

# =============================================================================
Resources:
# =============================================================================

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-6b3fd60c
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SecurityGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'

# =============================================================================
Outputs:
# =============================================================================
