version: '3'
services:
  app:
    build: .
    command: [yarn, dev]
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/app

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main
